### PR TITLE
Fix index out of range with invalid channel setting

### LINKED ISSUE #22: panic: runtime error: index out of range
I don't know what It happens but I can not achieve that the plugin work. 

I follow everything in the first part of configuration instructions.

https://github.com/mattermost/mattermost-plugin-aws-SNS#step-1-configure-plugin-in-mattermost

But when I see in the logs, I can notice, that the plugin does not start, this is the output log
```json
{"level":"debug","ts":1562371270.0409265,"caller":"plugin/hclog_adapter.go:33","msg":"starting plugin","plugin_id":"com.mattermost.aws-sns","wrapped_extras":"path/mattermost/plugins/com.mattermost.aws-sns/server/dist/plugin-linux-amd64args[/mattermost/plugins/com.mattermost.aws-sns/server/dist/plugin-linux-amd64]"}
{"level":"debug","ts":1562371270.0412219,"caller":"plugin/hclog_adapter.go:33","msg":"plugin started","plugin_id":"com.mattermost.aws-sns","wrapped_extras":"path/mattermost/plugins/com.mattermost.aws-sns/server/dist/plugin-linux-amd64pid1185"}
{"level":"debug","ts":1562371270.041272,"caller":"plugin/hclog_adapter.go:33","msg":"waiting for RPC address","plugin_id":"com.mattermost.aws-sns","wrapped_extras":"path/mattermost/plugins/com.mattermost.aws-sns/server/dist/plugin-linux-amd64"}
{"level":"debug","ts":1562371270.0472898,"caller":"plugin/hclog_adapter.go:33","msg":"using plugin","plugin_id":"com.mattermost.aws-sns","wrapped_extras":"version1"}
{"level":"debug","ts":1562371270.047629,"caller":"plugin/hclog_adapter.go:33","msg":"plugin address","plugin_id":"com.mattermost.aws-sns","wrapped_extras":"address/tmp/plugin913240609networkunixtimestamp2019-07-05T19:01:10.047-0500"}
{"level":"debug","ts":1562371270.052209,"caller":"plugin/hclog_adapter.go:35","msg":"panic: runtime error: index out of range","plugin_id":"com.mattermost.aws-sns"}
{"level":"debug","ts":1562371270.05225,"caller":"plugin/hclog_adapter.go:26","msg":"","plugin_id":"com.mattermost.aws-sns"}
{"level":"debug","ts":1562371270.0522683,"caller":"plugin/hclog_adapter.go:35","msg":"goroutine 22 [running]:","plugin_id":"com.mattermost.aws-sns"}
{"level":"debug","ts":1562371270.0522847,"caller":"plugin/hclog_adapter.go:35","msg":"main.(*Plugin).OnActivate(0xc00006ad80, 0xb3a900, 0xc00006ad80)","plugin_id":"com.mattermost.aws-sns"}
{"level":"debug","ts":1562371270.0522988,"caller":"plugin/hclog_adapter.go:35","msg":"\t/home/circleci/project/server/plugin.go:45 +0x651","plugin_id":"com.mattermost.aws-sns"}
{"level":"debug","ts":1562371270.0524123,"caller":"plugin/hclog_adapter.go:35","msg":"github.com/mattermost/mattermost-server/plugin.(*hooksRPCServer).OnActivate(0xc00000fa40, 0xc0000276b8, 0xc0000f9fc0, 0x0, 0x0)","plugin_id":"com.mattermost.aws-sns"}
{"level":"debug","ts":1562371270.052447,"caller":"plugin/hclog_adapter.go:35","msg":"\t/go/pkg/mod/github.com/mattermost/mattermost-server@v5.11.0+incompatible/plugin/client_rpc.go:219 +0x1b0","plugin_id":"com.mattermost.aws-sns"}
{"level":"debug","ts":1562371270.052461,"caller":"plugin/hclog_adapter.go:35","msg":"reflect.Value.call(0xc00021e300, 0xc000010ad8, 0x13, 0xb78cdb, 0x4, 0xc000054f18, 0x3, 0x3, 0xc000121c80, 0xc0000f9820, ...)","plugin_id":"com.mattermost.aws-sns"}
{"level":"debug","ts":1562371270.0526206,"caller":"plugin/hclog_adapter.go:35","msg":"\t/usr/local/go/src/reflect/value.go:447 +0x461","plugin_id":"com.mattermost.aws-sns"}
{"level":"debug","ts":1562371270.052683,"caller":"plugin/hclog_adapter.go:35","msg":"reflect.Value.Call(0xc00021e300, 0xc000010ad8, 0x13, 0xc00003ef18, 0x3, 0x3, 0x1, 0x0, 0x0)","plugin_id":"com.mattermost.aws-sns"}
{"level":"debug","ts":1562371270.052734,"caller":"plugin/hclog_adapter.go:35","msg":"\t/usr/local/go/src/reflect/value.go:308 +0xa4","plugin_id":"com.mattermost.aws-sns"}
{"level":"debug","ts":1562371270.0527842,"caller":"plugin/hclog_adapter.go:35","msg":"net/rpc.(*service).call(0xc000121ec0, 0xc000092d70, 0xc000027550, 0xc000027560, 0xc0000eb100, 0xc000224520, 0xa3b620, 0xc0000276b8, 0x16, 0xa3b660, ...)","plugin_id":"com.mattermost.aws-sns"}
{"level":"debug","ts":1562371270.0528166,"caller":"plugin/hclog_adapter.go:35","msg":"\t/usr/local/go/src/net/rpc/server.go:384 +0x14e","plugin_id":"com.mattermost.aws-sns"}
{"level":"debug","ts":1562371270.0528486,"caller":"plugin/hclog_adapter.go:35","msg":"created by net/rpc.(*Server).ServeCodec","plugin_id":"com.mattermost.aws-sns"}
{"level":"debug","ts":1562371270.0528626,"caller":"plugin/hclog_adapter.go:35","msg":"\t/usr/local/go/src/net/rpc/server.go:481 +0x42b","plugin_id":"com.mattermost.aws-sns"}
{"level":"debug","ts":1562371270.0534914,"caller":"plugin/hclog_adapter.go:33","msg":"plugin process exited","plugin_id":"com.mattermost.aws-sns","wrapped_extras":"path/mattermost/plugins/com.mattermost.aws-sns/server/dist/plugin-linux-amd64pid1185errorexit status 2"}
{"level":"error","ts":1562371270.0534205,"caller":"mlog/log.go:172","msg":"RPC call to OnActivate plugin failed.","plugin_id":"com.mattermost.aws-sns","error":"unexpected EOF"}
{"level":"error","ts":1562371270.0534651,"caller":"plugin/hclog_adapter.go:60","msg":"reading plugin stderr","plugin_id":"com.mattermost.aws-sns","wrapped_extras":"errorread |0: file already closed"}
```
 And this is the only part, than I thing is interesting
```json
{"level":"debug","ts":1562371270.052209,"caller":"plugin/hclog_adapter.go:35","msg":"panic: runtime error: index out of range","plugin_id":"com.mattermost.aws-sns"}
```

### PR DESCRIPTION
**Pull request by hanzei**
Fixes #22

### CODE REVIEW

File: server/plugin.go [hunk 1]
```diff
@@ -41,6 +42,10 @@ func (p *Plugin) OnActivate() error {
 	}
 
 	split := strings.Split(p.configuration.TeamChannel, ",")
+	if len(split) != 2 {
+		return errors.New("teamChannel setting doesn't follow the pattern $TEAM_NAME,$CHANNEL_NAME")
```
Comment (ali-farooq0) [inline server/plugin.go]: is it worth printing the `p.configuration.TeamChannel` variable so the person knows exactly where the mismatch is? for better forensics and better debugging. Just a thought.

Comment (hanzei) [reply server/plugin.go]: I don't really see the value. The admin has to go to the admin console any way, where he/she will see the value.
